# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('publications_bootstrap', '0003_db_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='catalogs',
        ),
        migrations.AddField(
            model_name='catalog',
            name='publications',
            field=models.ManyToManyField(blank=True, db_index=True, to='publications_bootstrap.Publication'),
        ),
    ]
