# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 20:19
from __future__ import unicode_literals

from django.db import migrations
from django.core import management

def load_data(apps, schema_editor):
	management.call_command('loaddata', 'initial_data.json')


class Migration(migrations.Migration):
	dependencies = [
		('publications', '0001_initial'),
	]

	operations = [
		migrations.RunPython(load_data),
	]
