# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-month', '-id']},
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, help_text='Only for a book.', max_length=32, unique=True, verbose_name='ISBN'),
        ),
    ]
